/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Federated search across every enabled catalog */
        get: {
            parameters: {
                query: {
                    q: string;
                    types?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            topResult: ({
                                /** @enum {string} */
                                type: "track";
                                item: components["schemas"]["Track"];
                            } | {
                                /** @enum {string} */
                                type: "album";
                                item: components["schemas"]["Album"];
                            } | {
                                /** @enum {string} */
                                type: "artist";
                                item: components["schemas"]["Artist"];
                            }) | null;
                            tracks: components["schemas"]["Track"][];
                            albums: components["schemas"]["Album"][];
                            artists: components["schemas"]["Artist"][];
                            playlists: components["schemas"]["Playlist"][];
                            nextOffset: number | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tracks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Canonical track id (trk_…) */
                            id: string;
                            title: string;
                            /** @description e.g. ["live"], ["remix"]; empty for the original */
                            versionTags: string[];
                            artists: {
                                id: string;
                                name: string;
                            }[];
                            album: {
                                id: string;
                                title: string;
                                images: {
                                    url: string;
                                    width?: number;
                                    height?: number;
                                }[];
                            } | null;
                            durationMs: number | null;
                            isrc: string | null;
                            explicit: boolean;
                            discNumber: number | null;
                            trackNumber: number | null;
                            images: {
                                url: string;
                                width?: number;
                                height?: number;
                            }[];
                            /** @description Best quality NAAD has measured for this track; null until a source has been resolved */
                            quality: components["schemas"]["TrackQuality"] | null;
                            links: {
                                catalog: string;
                                url: string | null;
                            }[];
                            liked: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            title: string;
                            albumType: string;
                            releaseDate: string | null;
                            label: string | null;
                            upc: string | null;
                            trackCount: number | null;
                            explicit: boolean;
                            artists: {
                                id: string;
                                name: string;
                            }[];
                            images: {
                                url: string;
                                width?: number;
                                height?: number;
                            }[];
                            tracks: components["schemas"]["Track"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                            images: {
                                url: string;
                                width?: number;
                                height?: number;
                            }[];
                            topTracks: components["schemas"]["Track"][];
                            albums: components["schemas"]["Album"][];
                            singles: components["schemas"]["Album"][];
                            related: components["schemas"]["Artist"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/playlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A playlist and a page of its items (external mirrors refresh from upstream when stale) */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            title: string;
                            description: string | null;
                            /** @description user | external | import */
                            origin: string;
                            inLibrary: boolean;
                            images: {
                                url: string;
                                width?: number;
                                height?: number;
                            }[];
                            trackCount: number;
                            items: {
                                items: {
                                    itemId: string;
                                    addedAt: string;
                                    track: components["schemas"]["Track"];
                                }[];
                                next: string | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        description?: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/v1/tracks/{id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve the best playable source for a track */
        get: {
            parameters: {
                query?: {
                    /** @description Highest tier wanted. "max" = best available. */
                    quality?: "max" | "hires" | "lossless" | "high" | "standard";
                    refresh?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            trackId: string;
                            selected: components["schemas"]["Source"];
                            alternatives: components["schemas"]["Source"][];
                            play: {
                                /** @description Signed stream URL; usable directly as <audio src> */
                                url: string;
                                expiresAt: string;
                                mimeType: string;
                                normalization: {
                                    gainDb: number;
                                    lufs: number | null;
                                } | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tracks/{id}/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve and redirect to the signed stream URL (handy for <audio src>) */
        get: {
            parameters: {
                query?: {
                    /** @description Highest tier wanted. "max" = best available. */
                    quality?: "max" | "hires" | "lossless" | "high" | "standard";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/player/prefetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Warm source resolution (and caching) for upcoming queue items */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        trackIds: string[];
                        /**
                         * @description Highest tier wanted. "max" = best available.
                         * @default max
                         * @enum {string}
                         */
                        quality?: "max" | "hires" | "lossless" | "high" | "standard";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accepted: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stream/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audio bytes (Range supported) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liked songs, newest first */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                likedAt: string;
                                track: components["schemas"]["Track"];
                            }[];
                            next: string | null;
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        trackIds: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        trackIds: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library/tracks/contains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    ids: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": boolean[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                savedAt: string;
                                album: components["schemas"]["Album"];
                            }[];
                            next: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                followedAt: string;
                                artist: components["schemas"]["Artist"];
                            }[];
                            next: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Playlist"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library/playlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save a playlist to the library */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        description?: string;
                        trackIds?: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/playlists/{id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/playlists/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add tracks (default: at the end) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        trackIds: string[];
                        /** @enum {string} */
                        position?: "start" | "end";
                        afterItemId?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            itemIds: string[];
                        };
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        itemIds: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/playlists/{id}/items/{itemId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move an item after another (afterItemId=null moves it to the top) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        afterItemId: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                playedAt: string;
                                msPlayed: number;
                                track: components["schemas"]["Track"];
                            }[];
                            next: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Report plays (batched). Plays shorter than 30 s do not count toward recommendations. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        listens: {
                            trackId: string;
                            /** Format: date-time */
                            startedAt: string;
                            msPlayed: number;
                            completed?: boolean;
                            context?: {
                                type: string;
                                id: string;
                            };
                            sourceProvider?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personalized home feed: recent, on repeat, "because you listened", charts, new releases */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sections: components["schemas"]["Section"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/radio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endless-radio queue from a seed (track:, artist:, album: or playlist:) */
        get: {
            parameters: {
                query: {
                    seed: string;
                    limit?: number;
                    exclude?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            seed: string;
                            tracks: components["schemas"]["Track"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    region?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sections: components["schemas"]["Section"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/new-releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    region?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            albums: components["schemas"]["Album"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mixes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily mixes built from your most-played artists */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            mixes: {
                                id: string;
                                title: string;
                                subtitle: string;
                                seedArtistId: string;
                                images: {
                                    url: string;
                                    width?: number;
                                    height?: number;
                                }[];
                                tracks: components["schemas"]["Track"][];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tracks/{id}/lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            trackId: string;
                            synced: {
                                timeMs: number;
                                text: string;
                            }[] | null;
                            plain: string | null;
                            source: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a Spotify, Apple Music or YouTube playlist/album into the library (async) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uri */
                        url: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Import"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Import"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Map a recording described elsewhere (title/artist/duration/ISRC) to a canonical track */
        get: {
            parameters: {
                query: {
                    title: string;
                    artist: string;
                    durationMs?: number;
                    isrc?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            confidence: number;
                            track: components["schemas"]["Track"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/art": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proxy and resize artwork for ambient extraction and privacy */
        get: {
            parameters: {
                query: {
                    src: string;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TrackQualityInput: {
            /** @enum {string} */
            tier: "standard" | "high" | "lossless" | "hires";
            codec: string;
            bitDepth: number | null;
            sampleRate: number | null;
            bitrateKbps: number | null;
            provider: string;
            verifiedAt: string;
        };
        TrackInput: {
            /** @description Canonical track id (trk_…) */
            id: string;
            title: string;
            /** @description e.g. ["live"], ["remix"]; empty for the original */
            versionTags: string[];
            artists: {
                id: string;
                name: string;
            }[];
            album: {
                id: string;
                title: string;
                images: {
                    url: string;
                    width?: number;
                    height?: number;
                }[];
            } | null;
            durationMs: number | null;
            isrc: string | null;
            explicit: boolean;
            discNumber: number | null;
            trackNumber: number | null;
            images: {
                url: string;
                width?: number;
                height?: number;
            }[];
            /** @description Best quality NAAD has measured for this track; null until a source has been resolved */
            quality: components["schemas"]["TrackQualityInput"] | null;
        };
        AlbumInput: {
            id: string;
            title: string;
            albumType: string;
            releaseDate: string | null;
            label: string | null;
            upc: string | null;
            trackCount: number | null;
            explicit: boolean;
            artists: {
                id: string;
                name: string;
            }[];
            images: {
                url: string;
                width?: number;
                height?: number;
            }[];
        };
        ArtistInput: {
            id: string;
            name: string;
            images: {
                url: string;
                width?: number;
                height?: number;
            }[];
        };
        PlaylistInput: {
            id: string;
            title: string;
            description: string | null;
            /** @description user | external | import */
            origin: string;
            inLibrary: boolean;
            images: {
                url: string;
                width?: number;
                height?: number;
            }[];
            trackCount: number;
        };
        SourceInput: {
            id: string;
            provider: string;
            /** @enum {string} */
            tier: "standard" | "high" | "lossless" | "hires";
            codec: string;
            container: string | null;
            mimeType: string;
            bitDepth: number | null;
            sampleRate: number | null;
            bitrateKbps: number | null;
            durationMs: number | null;
            delivery: string;
            matchScore: number;
            normalization: {
                gainDb: number;
                lufs: number | null;
            } | null;
            verifiedAt: string;
        };
        ProblemInput: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            requestId?: string;
            errors?: {
                path: string;
                message: string;
            }[];
        };
        SectionInput: {
            id: string;
            title: string;
            subtitle?: string;
            /** @constant */
            kind: "tracks";
            items: components["schemas"]["TrackInput"][];
        } | {
            id: string;
            title: string;
            subtitle?: string;
            /** @constant */
            kind: "albums";
            items: components["schemas"]["AlbumInput"][];
        } | {
            id: string;
            title: string;
            subtitle?: string;
            /** @constant */
            kind: "artists";
            items: components["schemas"]["ArtistInput"][];
        } | {
            id: string;
            title: string;
            subtitle?: string;
            /** @constant */
            kind: "playlists";
            items: components["schemas"]["PlaylistInput"][];
        };
        ImportInput: {
            id: string;
            url: string;
            service: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed";
            total: number | null;
            matched: number | null;
            playlistId: string | null;
            unmatched: {
                position: number;
                title: string;
                artists: string[];
            }[] | null;
            error: string | null;
            createdAt: string;
        };
        TrackQuality: {
            /** @enum {string} */
            tier: "standard" | "high" | "lossless" | "hires";
            codec: string;
            bitDepth: number | null;
            sampleRate: number | null;
            bitrateKbps: number | null;
            provider: string;
            verifiedAt: string;
        };
        Track: {
            /** @description Canonical track id (trk_…) */
            id: string;
            title: string;
            /** @description e.g. ["live"], ["remix"]; empty for the original */
            versionTags: string[];
            artists: {
                id: string;
                name: string;
            }[];
            album: {
                id: string;
                title: string;
                images: {
                    url: string;
                    width?: number;
                    height?: number;
                }[];
            } | null;
            durationMs: number | null;
            isrc: string | null;
            explicit: boolean;
            discNumber: number | null;
            trackNumber: number | null;
            images: {
                url: string;
                width?: number;
                height?: number;
            }[];
            /** @description Best quality NAAD has measured for this track; null until a source has been resolved */
            quality: components["schemas"]["TrackQuality"] | null;
        };
        Album: {
            id: string;
            title: string;
            albumType: string;
            releaseDate: string | null;
            label: string | null;
            upc: string | null;
            trackCount: number | null;
            explicit: boolean;
            artists: {
                id: string;
                name: string;
            }[];
            images: {
                url: string;
                width?: number;
                height?: number;
            }[];
        };
        Artist: {
            id: string;
            name: string;
            images: {
                url: string;
                width?: number;
                height?: number;
            }[];
        };
        Playlist: {
            id: string;
            title: string;
            description: string | null;
            /** @description user | external | import */
            origin: string;
            inLibrary: boolean;
            images: {
                url: string;
                width?: number;
                height?: number;
            }[];
            trackCount: number;
        };
        Source: {
            id: string;
            provider: string;
            /** @enum {string} */
            tier: "standard" | "high" | "lossless" | "hires";
            codec: string;
            container: string | null;
            mimeType: string;
            bitDepth: number | null;
            sampleRate: number | null;
            bitrateKbps: number | null;
            durationMs: number | null;
            delivery: string;
            matchScore: number;
            normalization: {
                gainDb: number;
                lufs: number | null;
            } | null;
            verifiedAt: string;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            requestId?: string;
            errors?: {
                path: string;
                message: string;
            }[];
        };
        Section: {
            id: string;
            title: string;
            subtitle?: string;
            /** @constant */
            kind: "tracks";
            items: components["schemas"]["Track"][];
        } | {
            id: string;
            title: string;
            subtitle?: string;
            /** @constant */
            kind: "albums";
            items: components["schemas"]["Album"][];
        } | {
            id: string;
            title: string;
            subtitle?: string;
            /** @constant */
            kind: "artists";
            items: components["schemas"]["Artist"][];
        } | {
            id: string;
            title: string;
            subtitle?: string;
            /** @constant */
            kind: "playlists";
            items: components["schemas"]["Playlist"][];
        };
        Import: {
            id: string;
            url: string;
            service: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed";
            total: number | null;
            matched: number | null;
            playlistId: string | null;
            unmatched: {
                position: number;
                title: string;
                artists: string[];
            }[] | null;
            error: string | null;
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
