/**
 * Phase A/B fixtures: real-shaped data (including long Devanagari titles) so the design system
 * is never reviewed against lorem ipsum. Deleted once Phase C wires the generated API client.
 */
import type { Album, Artist, Playlist, Source, Track } from './types';

const img = (seed: string, size = 500): { url: string } => ({
  url: `https://picsum.photos/seed/${seed}/${size}`,
});

export const artists: Artist[] = [
  { id: 'art_weeknd', name: 'The Weeknd', images: [img('weeknd')] },
  { id: 'art_arijit', name: 'Arijit Singh', images: [img('arijit')] },
  { id: 'art_pritam', name: 'Pritam', images: [img('pritam')] },
  { id: 'art_amitabh', name: 'Amitabh Bhattacharya', images: [img('amitabh')] },
];

export const albums: Album[] = [
  {
    id: 'alb_01m34h8ahbb1vrn8v3nw2k0p2n',
    title: 'The Highlights',
    albumType: 'album',
    releaseDate: '2021-02-05',
    label: 'Republic Records',
    upc: '00602508686208',
    trackCount: 14,
    explicit: false,
    artists: [artists[0]!],
    images: [{ url: 'https://c.saavncdn.com/396/The-Highlights-English-2021-20240207045714-500x500.jpg' }],
  },
  {
    id: 'alb_01m34h87p5bh35km3rvpvt7r7y',
    title: 'Brahmastra',
    albumType: 'album',
    releaseDate: '2022-07-06',
    label: 'Sony Music Entertainment India',
    upc: '00196589123456',
    trackCount: 9,
    explicit: false,
    artists: [artists[2]!, artists[1]!],
    images: [
      {
        url: 'https://c.saavncdn.com/871/Brahmastra-Original-Motion-Picture-Soundtrack-Hindi-2022-20221006155213-500x500.jpg',
      },
    ],
  },
];

export const sources: Source[] = [
  {
    id: 'src_1',
    provider: 'monochrome',
    tier: 'hires',
    codec: 'flac',
    container: 'flac',
    mimeType: 'audio/flac',
    bitDepth: 24,
    sampleRate: 44100,
    bitrateKbps: 1626,
    durationMs: 200040,
    delivery: 'redirect',
    matchScore: 1,
    normalization: { gainDb: -4.2, lufs: -9.8 },
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'src_2',
    provider: 'monochrome',
    tier: 'hires',
    codec: 'flac',
    container: 'flac',
    mimeType: 'audio/flac',
    bitDepth: 24,
    sampleRate: 96000,
    bitrateKbps: 3002,
    durationMs: 268164,
    delivery: 'redirect',
    matchScore: 1,
    normalization: { gainDb: -2.1, lufs: -11.4 },
    verifiedAt: new Date().toISOString(),
  },
];

export const tracks: Track[] = [
  {
    id: 'trk_01m34h8ag377tk945cmwgwj01p',
    title: 'Blinding Lights',
    versionTags: [],
    artists: [artists[0]!],
    album: { id: albums[0]!.id, title: albums[0]!.title, images: albums[0]!.images },
    durationMs: 200040,
    isrc: 'USUG11904206',
    explicit: false,
    discNumber: 1,
    trackNumber: 9,
    images: [{ url: 'https://c.saavncdn.com/396/The-Highlights-English-2021-20240207045714-500x500.jpg' }],
    quality: {
      provider: 'monochrome',
      tier: 'hires',
      codec: 'flac',
      bitDepth: 24,
      sampleRate: 44100,
      bitrateKbps: 1626,
      verifiedAt: new Date().toISOString(),
    },
  },
  {
    id: 'trk_01m34h87j97k357z25f6hpnrtj',
    title: 'केसरिया',
    versionTags: [],
    artists: [artists[2]!, artists[1]!, artists[3]!],
    album: { id: albums[1]!.id, title: albums[1]!.title, images: albums[1]!.images },
    durationMs: 268164,
    isrc: 'INS172203702',
    explicit: false,
    discNumber: 1,
    trackNumber: 3,
    images: [
      {
        url: 'https://c.saavncdn.com/871/Brahmastra-Original-Motion-Picture-Soundtrack-Hindi-2022-20221006155213-500x500.jpg',
      },
    ],
    quality: {
      provider: 'monochrome',
      tier: 'hires',
      codec: 'flac',
      bitDepth: 24,
      sampleRate: 96000,
      bitrateKbps: 3002,
      verifiedAt: new Date().toISOString(),
    },
  },
  {
    id: 'trk_kesariya_lofi',
    title: 'केसरिया (Lofi Flip)',
    versionTags: ['lofi'],
    artists: [artists[2]!, artists[1]!],
    album: null,
    durationMs: 240157,
    isrc: 'INS172220040',
    explicit: false,
    discNumber: null,
    trackNumber: null,
    images: [img('kesariya-lofi')],
    quality: {
      provider: 'jiosaavn',
      tier: 'high',
      codec: 'aac',
      bitDepth: null,
      sampleRate: 44100,
      bitrateKbps: 320,
      verifiedAt: new Date().toISOString(),
    },
  },
  {
    id: 'trk_tumhiho',
    title: 'Tum Hi Ho',
    versionTags: [],
    artists: [artists[1]!],
    album: null,
    durationMs: 262000,
    isrc: 'INS181303031',
    explicit: false,
    discNumber: null,
    trackNumber: null,
    images: [img('tumhiho')],
    quality: {
      provider: 'jiosaavn',
      tier: 'high',
      codec: 'aac',
      bitDepth: null,
      sampleRate: 44100,
      bitrateKbps: 320,
      verifiedAt: new Date().toISOString(),
    },
  },
  {
    id: 'trk_longtitle',
    title:
      'A Very Long Track Title That Keeps Going And Going To See How The Layout Truncates Gracefully On Small Screens',
    versionTags: ['live'],
    artists: [artists[0]!, artists[2]!],
    album: null,
    durationMs: 312000,
    isrc: null,
    explicit: true,
    discNumber: null,
    trackNumber: null,
    images: [],
    quality: {
      provider: 'youtube',
      tier: 'standard',
      codec: 'opus',
      bitDepth: null,
      sampleRate: 48000,
      bitrateKbps: 160,
      verifiedAt: new Date().toISOString(),
    },
  },
  {
    id: 'trk_nosource',
    title: 'Not Yet Resolved',
    versionTags: [],
    artists: [artists[3]!],
    album: null,
    durationMs: null,
    isrc: null,
    explicit: false,
    discNumber: null,
    trackNumber: null,
    images: [],
    quality: null,
  },
];

export const playlists: Playlist[] = [
  {
    id: 'pl_superhits',
    title: 'Hindi: India Superhits Top 50',
    description: 'By JioSaavn',
    origin: 'external',
    inLibrary: true,
    images: [img('superhits')],
    trackCount: 50,
  },
  {
    id: 'pl_roadtrip',
    title: 'Road Trip',
    description: null,
    origin: 'user',
    inLibrary: true,
    images: [],
    trackCount: 23,
  },
];
