/**
 * Phase A/B fixtures: real-shaped data (including long Devanagari titles) so the design system
 * is never reviewed against lorem ipsum. Deleted once Phase C wires the generated API client.
 */
import type { Album, Artist, Playlist, Track } from './types';

const img = (seed: string, size = 500): { url: string } => ({
  url: `https://picsum.photos/seed/${seed}/${size}`,
});

export const artists: Artist[] = [
  { id: 'art_weeknd', name: 'The Weeknd', images: [img('weeknd')] },
  { id: 'art_arijit', name: 'Arijit Singh', images: [img('arijit')] },
  { id: 'art_pritam', name: 'Pritam', images: [img('pritam')] },
  { id: 'art_amitabh', name: 'Amitabh Bhattacharya', images: [img('amitabh')] },
];

export const albums: Album[] = [
  {
    id: 'alb_afterhours',
    title: 'After Hours',
    albumType: 'album',
    releaseDate: '2020-03-20',
    label: 'Republic Records',
    upc: '00602508686208',
    trackCount: 14,
    explicit: true,
    artists: [artists[0]!],
    images: [img('afterhours')],
  },
  {
    id: 'alb_brahmastra',
    title: 'Brahmāstra Part One: Shiva',
    albumType: 'album',
    releaseDate: '2022-07-06',
    label: 'Sony Music Entertainment India',
    upc: '00196589123456',
    trackCount: 9,
    explicit: false,
    artists: [artists[2]!, artists[1]!],
    images: [img('brahmastra')],
  },
];

export const tracks: Track[] = [
  {
    id: 'trk_blinding',
    title: 'Blinding Lights',
    versionTags: [],
    artists: [artists[0]!],
    album: { id: albums[0]!.id, title: albums[0]!.title, images: albums[0]!.images },
    durationMs: 200040,
    isrc: 'USUG11904206',
    explicit: false,
    discNumber: 1,
    trackNumber: 9,
    images: [img('afterhours')],
    source: {
      id: 'src_1',
      provider: 'monochrome',
      tier: 'hires',
      codec: 'flac',
      container: 'flac',
      mimeType: 'audio/flac',
      bitDepth: 24,
      sampleRate: 44100,
      bitrateKbps: null,
      delivery: 'redirect',
      matchScore: 1,
      normalization: { gainDb: -4.2, lufs: -9.8 },
      verifiedAt: new Date().toISOString(),
    },
  },
  {
    id: 'trk_kesariya',
    title: 'केसरिया',
    versionTags: [],
    artists: [artists[2]!, artists[1]!, artists[3]!],
    album: { id: albums[1]!.id, title: albums[1]!.title, images: albums[1]!.images },
    durationMs: 268164,
    isrc: 'INS172203702',
    explicit: false,
    discNumber: 1,
    trackNumber: 3,
    images: [img('brahmastra')],
    source: {
      id: 'src_2',
      provider: 'monochrome',
      tier: 'hires',
      codec: 'flac',
      container: 'flac',
      mimeType: 'audio/flac',
      bitDepth: 24,
      sampleRate: 96000,
      bitrateKbps: null,
      delivery: 'redirect',
      matchScore: 1,
      normalization: { gainDb: -2.1, lufs: -11.4 },
      verifiedAt: new Date().toISOString(),
    },
  },
  {
    id: 'trk_kesariya_lofi',
    title: 'केसरिया (Lofi Flip)',
    versionTags: ['lofi'],
    artists: [artists[2]!, artists[1]!],
    album: null,
    durationMs: 240157,
    isrc: 'INS172220040',
    explicit: false,
    discNumber: null,
    trackNumber: null,
    images: [img('kesariya-lofi')],
    source: {
      id: 'src_3',
      provider: 'jiosaavn',
      tier: 'high',
      codec: 'aac',
      container: 'mp4',
      mimeType: 'audio/mp4',
      bitDepth: null,
      sampleRate: 44100,
      bitrateKbps: 320,
      delivery: 'redirect',
      matchScore: 0.94,
      normalization: null,
      verifiedAt: new Date().toISOString(),
    },
  },
  {
    id: 'trk_tumhiho',
    title: 'Tum Hi Ho',
    versionTags: [],
    artists: [artists[1]!],
    album: null,
    durationMs: 262000,
    isrc: 'INS181303031',
    explicit: false,
    discNumber: null,
    trackNumber: null,
    images: [img('tumhiho')],
    source: {
      id: 'src_4',
      provider: 'jiosaavn',
      tier: 'high',
      codec: 'aac',
      container: 'mp4',
      mimeType: 'audio/mp4',
      bitDepth: null,
      sampleRate: 44100,
      bitrateKbps: 320,
      delivery: 'redirect',
      matchScore: 0.98,
      normalization: null,
      verifiedAt: new Date().toISOString(),
    },
  },
  {
    id: 'trk_longtitle',
    title:
      'A Very Long Track Title That Keeps Going And Going To See How The Layout Truncates Gracefully On Small Screens',
    versionTags: ['live'],
    artists: [artists[0]!, artists[2]!],
    album: null,
    durationMs: 312000,
    isrc: null,
    explicit: true,
    discNumber: null,
    trackNumber: null,
    images: [],
    source: {
      id: 'src_5',
      provider: 'youtube',
      tier: 'standard',
      codec: 'opus',
      container: 'webm',
      mimeType: 'audio/webm',
      bitDepth: null,
      sampleRate: 48000,
      bitrateKbps: 160,
      delivery: 'materialize',
      matchScore: 0.81,
      normalization: null,
      verifiedAt: new Date().toISOString(),
    },
  },
  {
    id: 'trk_nosource',
    title: 'Not Yet Resolved',
    versionTags: [],
    artists: [artists[3]!],
    album: null,
    durationMs: null,
    isrc: null,
    explicit: false,
    discNumber: null,
    trackNumber: null,
    images: [],
  },
];

export const playlists: Playlist[] = [
  {
    id: 'pl_superhits',
    title: 'Hindi: India Superhits Top 50',
    description: 'By JioSaavn',
    origin: 'external',
    inLibrary: true,
    images: [img('superhits')],
    trackCount: 50,
  },
  {
    id: 'pl_roadtrip',
    title: 'Road Trip',
    description: null,
    origin: 'user',
    inLibrary: true,
    images: [],
    trackCount: 23,
  },
];
